//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Model.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineStoreMVCEntities : DbContext
    {
        public OnlineStoreMVCEntities()
            : base("name=OnlineStoreMVCEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CMSCategory> CMSCategories { get; set; }
        public virtual DbSet<CMSNews> CMSNews { get; set; }
        public virtual DbSet<ShareCategory> ShareCategories { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<SystemConfig> SystemConfigs { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
    }
}
